spring.application.name=automaticMail
server.port=7777


# SMTP provider of mail Service
spring.mail.host=smtp.gmail.com

# secured TLS port
spring.mail.port=587
spring.mail.username=yvankamsu88@gmail.com
spring.mail.password=ueuc vskp zgrj dzme

# active secure connexion
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# H2 console
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update